name: "Build FHIR IG"
description: "Build IG using the IG publisher"
inputs:
  sushi-version:
    description: "Version of sushi to use for the generation"
    required: true
  working-directory:
    description: "Root directory of the FSH Sushi project"
    required: false
    default: "."
runs:
  using: composite
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: "18"
    - run: npm install -g npm install -g fsh-sushi@${{ inputs.sushi-version }}
      shell: bash
    - working-directory: ${{ inputs.working-directory }}
      run: sushi
      shell: bash
    - working-directory: ${{ inputs.working-directory }}
      run: |
        if [[ `git status --porcelain` ]]; then
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.${INPUT_ORGANIZATION_DOMAIN}"
          git add fsh-generated
          git commit -m "[GEN] Generate FHIR profiles"
          git push origin ${GITHUB_REF_NAME}
        fi
      shell: bash
